from enum import StrEnum


class UserRole(StrEnum):
	ADMIN = "ADMIN"
	INVENTORY_MANAGER = "INVENTORY_MANAGER"
	WAREHOUSE_STAFF = "WAREHOUSE_STAFF"


class DocumentStatus(StrEnum):
	DRAFT = "DRAFT"
	WAITING = "WAITING"
	READY = "READY"
	DONE = "DONE"
	CANCELED = "CANCELED"


class MovementType(StrEnum):
	RECEIPT = "RECEIPT"
	DELIVERY = "DELIVERY"
	TRANSFER_IN = "TRANSFER_IN"
	TRANSFER_OUT = "TRANSFER_OUT"
	ADJUSTMENT_IN = "ADJUSTMENT_IN"
	ADJUSTMENT_OUT = "ADJUSTMENT_OUT"
	INITIAL_STOCK = "INITIAL_STOCK"
