import { useEffect, useState } from "react";
import api from "../services/api";

export default function Dashboard() {
	const [summary, setSummary] = useState(null);
	const [alerts, setAlerts] = useState([]);
	const [error, setError] = useState("");
	useEffect(() => { Promise.all([api.get("/dashboard/summary"), api.get("/dashboard/low-stock")]).then(([summaryResponse, alertResponse]) => { setSummary(summaryResponse.data); setAlerts(alertResponse.data); }).catch(() => setError("Dashboard data could not be loaded.")); }, []);
	const cards = summary ? [["Products in stock", summary.total_products_in_stock, "active catalog"], ["Low stock", summary.low_stock_items, "needs attention"], ["Out of stock", summary.out_of_stock_items, "requires action"], ["Pending receipts", summary.pending_receipts, "inbound"], ["Pending deliveries", summary.pending_deliveries, "outbound"], ["Scheduled transfers", summary.scheduled_transfers, "in motion"]] : [];
	return <section className="content"><div className="page-intro"><div><span className="eyebrow">Tuesday, September 26, 2026</span><h2>Operations overview</h2><p>Stay ahead of the next stock decision.</p></div><button className="primary-button">+ New operation</button></div>{error && <div className="error-message">{error}</div>}<div className="metric-grid">{cards.map(([label, value, caption]) => <article className="metric-card" key={label}><span>{label}</span><strong>{value}</strong><small>{caption}</small></article>)}</div><div className="dashboard-grid"><article className="panel"><div className="panel-heading"><div><span className="eyebrow">Attention queue</span><h3>Low stock alerts</h3></div><a href="/products">View products</a></div>{alerts.length ? <div className="alert-list">{alerts.map((alert) => <div className="alert-row" key={alert.product_id}><span className="alert-icon">!</span><div><strong>{alert.name}</strong><small>{alert.sku}</small></div><b>{alert.available_quantity} / {alert.reorder_level}</b></div>)}</div> : <div className="empty-state">All active products are above their reorder levels.</div>}</article><article className="panel activity-panel"><div className="panel-heading"><div><span className="eyebrow">Workflow</span><h3>Next actions</h3></div></div><div className="action-list"><a href="/receipts"><span>01</span><div><strong>Receive inbound stock</strong><small>Turn a supplier delivery into inventory</small></div>→</a><a href="/deliveries"><span>02</span><div><strong>Validate a delivery</strong><small>Keep outbound stock accurate</small></div>→</a><a href="/ledger"><span>03</span><div><strong>Review stock ledger</strong><small>Trace every quantity change</small></div>→</a></div></article></div></section>;
}
