"""scope location codes by warehouse

Revision ID: b6778540bc3b
Revises: 5c53b3aee5de
Create Date: 2026-09-26 15:28:32.008070
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b6778540bc3b'
down_revision: Union[str, Sequence[str], None] = '5c53b3aee5de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_location_warehouse_code', 'locations', ['warehouse_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_location_warehouse_code', 'locations', type_='unique')
    # ### end Alembic commands ###
